### ISSUE TITLE
Odoo-jira : error message when update Modul list

### ISSUE THREAD

**Issue by yboujraf** [openbig/odoo-jira#1]
Dear,

I tried to install the module Odoo-jira but when trying to update Module list, I got an error message.

Please find below :

``` javascript
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 412, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 416, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/odoo/odoo-server/openerp/http.py", line 1310, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/odoo/odoo-server/addons/project_issue_jira/__init__.py", line 4, in <module>
    import project_issue_jira
  File "/odoo/odoo-server/addons/project_issue_jira/project_issue_jira.py", line 2, in <module>
    from jira.client import JIRA
ImportError: No module named jira.client
```

I hope it can help you.

Best Regards,
Youssef

**Comment by scigghia** [comment]
Hi,
is this solved? is there any library we can install to go on?

**Comment by scigghia** [comment]
Solved with "pip install JIRA"
:)
